CREATE TABLE CLIENTE (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (100)
);

CREATE TABLE PRODUTO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR (100),
    VALOR_UNITARIO  NUMERIC (20,2)
);

CREATE TABLE PEDIDO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INTEGER REFERENCES CLIENTE (ID),
    DT_PEDIDO TIMESTAMP,
    TOTAL_PEDIDO NUMERIC (20,2)
);

CREATE TABLE ITEM_PEDIDO (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PRODUTO_ID INTEGER REFERENCES PRODUTO (ID),
    PEDIDO_ID INTEGER REFERENCES PEDIDO (ID),
    QUANTIDADE INTEGER
);